README.md
operator/redisfailover/factory.go

Fixes # .
This PR makes a redis-operator not cluster wide but namespace scoped

Allow Operator to Be Namespace-Scoped

---

api/redisfailover/v1/types.go
api/redisfailover/v1/zz_generated.deepcopy.go
charts/redisoperator/crds/databases.spotahome.com_redisfailovers.yaml
manifests/databases.spotahome.com_redisfailovers.yaml
manifests/kustomize/base/databases.spotahome.com_redisfailovers.yaml
operator/redisfailover/ensurer.go
operator/redisfailover/service/client.go
operator/redisfailover/service/constants.go
operator/redisfailover/service/generator.go
operator/redisfailover/service/names.go
service/k8s/k8s.go
service/k8s/networkpolicy.go

Fixes # .
Purpose of this PR is to give a redis-operator ability to create a NetworkPolicy object
The problem we want to solve by this PR is to stop sentinel's servers join `other` sentinel servers from different namespaces.

Deploy and Manage Optional NetworkPolicy

---

api/redisfailover/v1/types.go
api/redisfailover/v1/zz_generated.deepcopy.go
charts/redisoperator/crds/databases.spotahome.com_redisfailovers.yaml
operator/redisfailover/service/generator.go

This PR adds ability to configure affinity for HAProxy in redis-operator
```
spec:
haproxy:
redisHost: "redis-haproxy"
replicas: 1
image: "haproxy:2.4"
affinity:
podAntiAffinity:
requiredDuringSchedulingIgnoredDuringExecution:
- labelSelector:
matchExpressions:
- key: <%= env %>.powerapp.cloud/redis
operator: In
values:
- server
topologyKey: physicalmachine
sentinel:
replicas: 3
redis:
replicas: 2
```

Affinity Config For HAProxy

---

operator/redisfailover/service/client.go
operator/redisfailover/service/generator.go

This PR adds component labels `redisfailovers.databases.spotahome.com/component`  for `redis`, `sentinel`, `haproxy`

FVR-45: Add Explicit Component Labels

---

operator/redisfailover/handler.go

This PR will fix a bug when status.ObservedGeneration  does not match with Generation of resource after deploy was made

Update status.observedGeneration w/ Latest Ver

---

operator/redisfailover/service/generator.go

This PR make HAProxy `image` and `hostName` optional. By default `image` will be `haproxy:2.4` and `hostname` will be `redis-haproxy`

Haproxy Optional Parameters

---

operator/redisfailover/handler.go

This PR addresses the Redis reconciliation error. 
When deploying a resource using Krane, it is crucial to compare the `ObservedGeneration` of the RedisFailover resource to its status `ObservedGeneration`. If there's a discrepancy, it indicates that the resource is undergoing an update. The operator must then adjust the `status` to ensure Krane waits for the resource update to complete.

Update Status When CR Modified

---

operator/redisfailover/service/check.go
operator/redisfailover/service/check_test.go

Fix custom status conditions / transitions when the cluster is set to bootstrap.
When the RedisFailover is set to bootstrap its data from another Redis instance, the status / condition never transitions away form "Initializing RedisFailover..." even if the Redis cluster comes up. 
The operator asks the checker if the all of the resources for the RedisFailover are in a running status - `IsClusterRunning`. However, the logic of `IsClusterRunning` doesn't consider that when the RedisFailover is boottrapping, the operator purposefully does NOT create the Sentinel resource. 
The `IsClusterRunning` method is only ever used during this check in the status updating `handler` logic we added:
https://github.com/powerhome/redis-operator/blob/d9cd24fcfad5d6013a69f25877fe8bba4b01f43b/operator/redisfail …

Fix status when bootstrapping

---

client/k8s/clientset/versioned/typed/redisfailover/v1/fake/fake_redisfailover.go
docker/development/Dockerfile

Closes: https://nitro.powerhrg.com/runway/backlog_items/FVR-118
Fix the `make unit-test` target
First, fix the redisfailvoer module name in the Fake RedisFailover. This is causing the unit tests to fail because the RedisFailvoer module is imported a `v1`, not `redisfailoverv1`. 
Second, fixes the development image build on Apple Silicon. The development image Dockerfile fetches the `mockery` library using the container OS' architecture - `$(uname -m)`. [Alpine](https://wiki.alpinelinux.org/wiki/Architecture) and [Mockery](https://github.com/vektra/mockery/releases/tag/v2.32.0) use different names for ARM architectures; `aarch64` and `amd64` respectively. 
If anyone has an intel-based development machine I'd be grateful for a quick validation that `make unit-test` still builds the dev …

Fix unit tests

---

CHANGELOG.md
mocks/service/k8s/Services.go
operator/redisfailover/service/generator.go
service/k8s/poddisruptionbudget.go
service/k8s/poddisruptionbudget_test.go

Summary
=======
Closes: https://nitro.powerhrg.com/runway/backlog_items/FVR-76
Fix Pod Disruption Budget API deprecation warning on Kube 1.21+
Cluster Info
-------------
```
$ pac "kubectl --context kind-test --namespace redis-operator-test version"
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.14", GitCommit:"0f77da5bd4809927e15d1658fb4aa8f13ad890a5", GitTreeState:"clean", BuildDate:"2022-06-15T14:17:29Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.14", GitCommit:"0f77da5bd4809927e15d1658fb4aa8f13ad890a5", GitTreeState:"clean", BuildDate:"2023-06-15T02:44:26Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/arm64"}
```
Before - `image: …

[FVR-76] Fix kube 1.21 DisruptionBudget deprecation warning

---

mocks/service/k8s/Services.go
test/integration/redisfailover/creation_test.go

Part of: https://nitro.powerhrg.com/runway/backlog_items/FVR-93
Fix the generated mocks
=======================
`make test` is currently failing because the generated mock references an undefined variable:
```
Error: mocks/service/k8s/Services.go:565:3: undefined: r1
Error: mocks/service/k8s/Services.go:567:3: undefined: r1
Error: mocks/service/k8s/Services.go:570:13: undefined: r1
```
This was probably introduced in merge from the upstream and not caught because we're still in the process of setting CI in this fork. 
Fix the integration tests
==========================
The integration tests have also been broken since we added a configurable port to the Sentinels:
```
Error: test/integration/redisfailover/creation_test.go:250:52: not enough arguments in call to …
```

Fix generated mocks

---

.github/workflows/ci.yaml

Summary
============
Add the current PAC kube version to the testing matrix.
Context
==========
The integration test suite doesn't test the operator against the version of kube we use internally. While we ARE actively upgrading our clusters, we _ought_ to make sure the integration tests are run against the versions of kube we intend to support. This change adds said version to the testing matrix.
Part of: https://nitro.powerhrg.com/runway/backlog_items/FVR-93

Add kube 1.12.14 to integration-tests

---

CHANGELOG.md
Makefile
mocks/operator/redisfailover/service/RedisFailoverClient.go
operator/redisfailover/ensurer.go
operator/redisfailover/service/client.go
operator/redisfailover/service/constants.go
operator/redisfailover/service/generator.go
operator/redisfailover/service/generator_test.go
operator/redisfailover/service/names.go

In #4, we added a NetworkPolicy. The intent was to prevent the Redis and/or Sentinel pods from differing RedisFailovers from joining up with one another (See: https://github.com/spotahome/redis-operator/issues/550). These policies have proven to be too coarsely grained. We end up deploying supplemental NetworkPolicies to allow ingress traffic. 
This change narrows the scope of the NetworkPolicies manged by the operator. One policy allows traffic to the Redis node pods ONLY on the redis port and monitoring port for traffic originating from within the namespace. The other policy allows traffic to the Sentinel pods ONLY on the sentinel port for traffic originating from within the namespace. All other traffic to these pods will be dropped. 
Connections to the HAProxy pods - IE access to the …

Use more targeted NetworkPolicies

---

CHANGELOG.md
Makefile

Updates make targets to produce public powerhome/redis-operator images at https://hub.docker.com/r/powerhome/redis-operator

Setup public image repository

---

.github/workflows/ci.yaml

The CI workflow has always intended to run when the master branch changes, however the workflow definition is targeting the wrong branch name. 
With this change, CI should run on the head commits of all PRs, AND the master branch.

Run ci on the master branch

---

.github/workflows/ci.yaml
Makefile
docker-bake.hcl

Add Github Actions to build and publish images to the [public docker hub image repository](https://hub.docker.com/repository/docker/powerhome/redis-operator/general).
Images are built only for commits with passing linter, unit and integration test checks.
Images are built for...:
- the HEAD commits of PR branches where the base branch is `master`. An image tag with the PR Branch's HEAD commit's git SHA will be produced.
- merges into the `master` branch. An image tag with the `master` branch's HEAD commit's git SHA will be produced.
- new tags pushed into the Github repository. An image tag with the git tag's name will be produced.
Changes of note:
The replaces the `Makefile` targets intended to build and push images. Instead we'll rely on the publicly available Github Actions published …

Automate image publishing

---

.github/workflows/ci.yaml
CHANGELOG.md
Makefile
docker-bake.hcl
docker/development/Dockerfile
docs/development.md

Related to: #30
Using the image building infrastructure added in #30, this moves the
build configuration of the development tooling image into docker bake.
Additionally, this removes vestigial configuration and targets from
the `Makefile`. This also normalizes the `Makefile` target names; for
easier discover-ability of alike tasks. For example, all testing
related targets now start with `test-`; `test-unit` for unit tests,
`tests-helm` for chart tests, etc. The project's developer
documentation is also updated to reflect these changes.

Use docker bake to build development image

---

mocks/operator/redisfailover/service/RedisFailoverClient.go

Ran the `make generate` target locally while preparing a branch for the 1.8.0 release. I'm not entirely sure what happened, but the client generator wants to move and fix the documentation of the `DestroySentinelResources` method that was added in https://github.com/powerhome/redis-operator/pull/33.

Run make generate to fix DestroySentinelResource

---

CHANGELOG.md
Makefile

This PR introducing new redis-operator release version

Release v2.0.0

---

CHANGELOG.md
api/redisfailover/v1/defaults.go
api/redisfailover/v1/validate.go
api/redisfailover/v1/validate_test.go

Sets a default HAProxy image when one is not specified in the RedisFailover CR. When the RedisFailover includes a HAProxy Spec, the operator errors unless an Image attribute is present.

Add default haproxy image

---

CHANGELOG.md
mocks/operator/redisfailover/service/RedisFailoverClient.go
operator/redisfailover/ensurer.go
operator/redisfailover/ensurer_test.go
operator/redisfailover/service/client.go

Fixes: https://github.com/powerhome/redis-operator/issues/48
This PR aims to address an issue introduced in release 2.0.1, where the logic for generating network policy resources by the operator was changed. From version 2.0.1 onwards, the operator no longer generates network policies for Redis but failed to remove existing policies generated prior to this version. This PR introduces a check and removal process for that leftover network policiy.

Remove orphaned network policy resource

---

CHANGELOG.md
Makefile

Prepare the repository for tagging / release of version 2.1.0.
Note, this release contains a [fix](https://github.com/powerhome/redis-operator/pull/49) for https://github.com/powerhome/redis-operator/issues/48 - hence the minor version upgrade.
References
----------
- https://semver.org/#what-do-i-do-if-i-accidentally-release-a-backward-incompatible-change-as-a-minor-version

Prepare release v2.1.0

---

service/k8s/statefulset.go
service/k8s/statefulset_test.go

An alternative approach to restarting StatefulSet-related pods is to delete the StatefulSet itself and allow the operator to automatically recreate it during the next reconciliation loop. This differs from the previous implementation made in https://github.com/powerhome/redis-operator/pull/54

[FVR-182] Restarting Pods Through STS Deletion

---

CHANGELOG.md
api/redisfailover/v1/defaults.go
operator/redisfailover/service/generator.go

There is a brief period of time during a Redis replica restart when HAProxy can send writes to it; causing the following error:
```
READONLY You can't write against a read only replica.
```
This is because HAProxy (< 3.1.0) always treats newly detected backends as immediately UP - ready to serve traffic - UNTIL they failed their checks. HAProxy v3.1.0 adds the ability to configure a backend's initial state - init-state - and how/when it HAProxy determines that the backend is ready to receive traffic.
This changes the HAProxy configuration so that a new Redis node is disqualified from client receiving traffic until HAProxy determines that the node is indeed a "master" node.
This also updates the default operator's HAProxy image accordingly to receive the `init-state` HAProxy configuration …

Prevent connections to replica on replica restart

---

.github/workflows/ci.yaml

Related to: 
- https://github.com/medyagh/setup-minikube/issues/565
- https://github.com/powerhome/redis-operator/actions/runs/12774059053/job/35608701152#step:5:78
```
Preparing to unpack .../socat_1.8.0.0-4build3_amd64.deb ...
Unpacking socat (1.8.0.0-4build3) ...
Setting up socat (1.8.0.0-4build3) ...
Processing triggers for man-db (2.12.0-4build2) ...
Running kernel seems to be up-to-date.
No services need to be restarted.
No containers need to be restarted.
No user sessions are running outdated binaries.
No VM guests are running outdated hypervisor (qemu) binaries on this host.
/usr/bin/lsb_release --short --codename
noble
Error: Unexpected HTTP response: 404
```

Fix integration test runner

---

operator/redisfailover/service/generator.go

Some clients do not gracefully handle when a failover occurs; they keep the established connection open. When the redis node comes back up as a replica, the client recieves an error indicating that they cannot write against the replica:
```
READONLY You can't write against a read only replica
```
This closes client connections to a redis node when haproxy detects that it is in a "down" state. The idea is that the clients will recognize they need to reestablish a connection. 
References:
- https://docs.haproxy.org/3.1/configuration.html#5.2-on-marked-down

haproxy: disconnect clients when node is demoted to replica

---

.github/workflows/ci.yaml

Fix buildx and bake action compatibility issues in the `ci` GitHub workflow.
- https://github.com/powerhome/redis-operator/actions/runs/12935287363/job/36078911603
```
docker/bake-action < v5 is not compatible with buildx >= 0.20.0, please update your workflow to latest docker/bake-action or use an older buildx version.
```

Fix buildx and bake action compatibility issues

---

portal.yml

This is to change the owner of this operator from the now defunct Forever People team to Guardians of the Galaxy.

Forever People was merged into GOG

---

CHANGELOG.md
operator/redisfailover/service/generator.go
operator/redisfailover/service/generator_test.go

Bring the haproxy service labels into a similar shape as the redis
service labels. Makes it easier to select just the haproxy service by
its labels.
Current Redis "Master" Service labels:
``` yaml
metadata:
labels:
app.kubernetes.io/component: redis
app.kubernetes.io/managed-by: redis-operator
app.kubernetes.io/name: redis
app.kubernetes.io/part-of: redis-failover
redisfailovers-role: master
redisfailovers.databases.spotahome.com/name: redis
```
Additions to the Haproxy Service labels:
``` diff
metadata:
labels:
+   app.kubernetes.io/component: haproxy
app.kubernetes.io/managed-by: redis-operator
+   app.kubernetes.io/name: redis
+   app.kubernetes.io/part-of: redis-failover
+   redisfailovers-role: master
redisfailovers.databases.spotahome.com/name: redis
```

Haproxy: Fix service labels

---

CHANGELOG.md

I messed up the changelog version number in https://github.com/powerhome/redis-operator/pull/67.

Fix CHANGELOG.md version

---

operator/redisfailover/service/check.go
operator/redisfailover/service/check_test.go

Starting with version [2.4.0 of the redis-operator](https://github.com/powerhome/redis-operator/releases/tag/v4.3.0), we are removing HAProxy from the  cluster in bootstrap mode. 
However, the cluster health check still expects HAProxy to be present. 
```
if rFailover.Bootstrapping() && !rFailover.SentinelsAllowed() {
return r.IsRedisRunning(rFailover) && r.IsHAProxyRunning(rFailover)
}
```
As a result, the health check fails, preventing the Redis custom resource from updating its status and causing the deployment to fail.
Logic now distinguishes between:
- Bootstrap mode with sentinels disabled → only Redis must be running.
- Bootstrap mode with sentinels allowed → Redis and Sentinel must be running.
- Normal mode → Redis, Sentinel, and HAProxy must all be running.

[GOG-1162] Fix Cluster Health Check to Skip HAProxy Validation in Bootstrap Mode

---

.github/workflows/ci.yaml
CHANGELOG.md

In an effort to keep maintenance burden more reasonable over time,
we're officially support for kube versions 1.22 and older.

Drop support for kube <= 1.22

---

example/operator/all-redis-operator-resources.yaml
example/operator/roles.yaml
manifests/kustomize/components/rbac/clusterrole.yaml

A long, long time ago we added the network policy resource[^1] and a
status field[^2] to the custom resource; the operator is meant to
manage these. However, we didn't updated the operator's clusterrole
templates to reflect the resources necessary to do this. Let's fix
that here.
[^1]: https://github.com/powerhome/redis-operator/pull/2
[^2]: https://github.com/powerhome/redis-operator/pull/7

Fix operator's clusterrole kustomize template and examples
